### ISSUE TITLE
Hacktoberfest no code: case studies!

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-docs#114]
This issue is specifically intended as a no-code contribution for [hacktoberfest](https://speckle.systems/hacktoberfest-2022/):

- write one (or more!) comprehensive case studies on using Speckle on a project
- the case study can be in written form (blog post) or video

To submit: Make a PR to the repo readme with a link to what you have made.

**NB: If you don't know how to create a PR to make this qualify as a contribution, let us know in the comments and we will do so for you! ✌**

**Comment by devtayade** [comment]
@teocomi  hey i really want to work on this issue. this can be my first step towards open source. can you please assign me this issue ?

**Comment by teocomi** [comment]
Sure thing! @devtayade
And we're accepting multiple contributions, so other feel free to join as well :)
