### ISSUE TITLE
Hacktoberfest no code: advocacy & events!

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-docs#115]
This issue is specifically intended as a no-code contribution for [hacktoberfest](https://speckle.systems/hacktoberfest-2022/), it could be any of the following:

- use compelling social media strategies to promote Speckle to a wide audiance
- write a blog post on Speckle
- organize a presentation on Speckle at your company
- organize a meetup
- if in doubt, just ask in the comments!

**NB: If you don't know how to create a PR to make this qualify as a contribution, let us know in the comments and we will do so for you! ✌**

**Comment by kimbengfaith** [comment]
please i don't understand what you meant by " write a blog post on Speckle" the statement is not really clear

**Comment by Bennykillua** [comment]
@teocomi Can I make video content of your contents and share so it reach a wider audience

**Comment by teocomi** [comment]
> @teocomi Can I make video content of your contents and share so it reach a wider audience

That'd be great, thanks!

> please i don't understand what you meant by " write a blog post on Speckle" the statement is not really clear

That means writing a blog post on our software solutions and how users/organizations can benefit from it.

**Comment by rsarthak** [comment]
I want to work on this, please assign it to me.

**Comment by rsarthak** [comment]
@teocomi  can you guide me on what to write in the presentation?

**Comment by jsdbroughton** [comment]
> can you guide me on what to write in the presentation?

This is best suited to someone in a position to be using the Speckle Platform. While this doesn't guarantee enlightenment, it would given proper context to any such advocacy
