### ISSUE TITLE
Hacktoberfest no code: Sample Models

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-docs#117]
This issue is specifically intended as a no-code contribution for [hacktoberfest](https://speckle.systems/hacktoberfest-2022/):

### Description
Create a model using your preferred choice of modelling software. This model will be used for internal tests and product demos. 

> ⚠ Model must be created by you using the native software. So don't download a model from the web and upload it pls.

You can create a model of:

- 🗼 High-rise Tower
- 🏢 Commercial Architecture (store, showroom, bank)
- 🏠 Residential Architecture (Single-family, multi-family, apartment etc.)
- 🪑 Interior Design (House, Office, hotel, restaurant)
- 🏟 Stadium
- 🌳 Landscape Design
- 👡 Product Design
- 🏵 Pavilion

### Examples of softwares you can use:

- Revit/Dynamo
- Archicad
- Sketchup
- Rhino/Grasshopper
- Blender

or any other modeling software Speckle has a connector for.

### To submit
- Upload your model to any file hosting service (WeTransfer, Google Drive, Dropbox etc.) 
- Make a PR to this repo readme with its link and a brief description of what it is
- OR just drop it here as a comment 💬

**Note:**  Bonus points if you can also use the Speckle Connector for your authoring application and upload your model to a Speckle Stream!

NB: If you don't know how to create a PR to make this qualify as a contribution, just post it as a comment, and we will make the PR for you! ✌

**Comment by Ep1c-paav** [comment]
hey I am new to this. can you just guide me on the submission process.

**Comment by bimgeek** [comment]
Hey @Ep1c-paav 👋,

Upload your model to any file hosting service (WeTransfer, Google Drive, Dropbox etc.) and add its link (along with a brief description of what it is) here as a comment💬. That's it!

**Comment by Shoray2002** [comment]
Hey I have created my model and wish to make a PR 
Can you tell me what changes exactly I have to make to my fork before the PR

**Comment by didimitrie** [comment]
Hey @Shoray2002, see above @bimgeek's reply! 
> Upload your model to any file hosting service (WeTransfer, Google Drive, Dropbox etc.) and add its link (along with a brief description of what it is) here as a comment💬. That's it!

**Comment by Shoray2002** [comment]
Oh I thought I had to make a PR. nevermind I will add a comment 
Thanks @didimitrie

**Comment by teocomi** [comment]
@Shoray2002 if you want it to count towards the DO Hacktoberfest, please make a pr to this repo readme with a link to the model, otherwise, a comment here as said before works :)

**Comment by Shoray2002** [comment]
This is the testing model I used for a game I was working on earlier
It's a closed rectangular model with stairs, platforms, and even a fort-like structure
[Mega Drive Link](https://mega.nz/file/F0FikA4C#uOotjeQs37I4siB6Ny2zv-ZHjpePWOYCLRANn7gXpNc)
![image](https://user-images.githubusercontent.com/76423272/193403846-776dc523-4a97-4a81-be69-a7aa9e9011e7.png)

**Comment by Shoray2002** [comment]
> @Shoray2002 if you want it to count towards the DO Hacktoberfest, please make a pr to this repo readme with a link to the model, otherwise, a comment here as said before works :)

Should I just add the link to the model wherever? or is there any specific place you want it?

**Comment by trishitapingolia** [comment]
I have made a 3d model of Laughing budhha in blender. Here's the link: https://1drv.ms/u/s!Ak9cKgIuUoPCrTT3re8xnF_eGaJR?e=Nou9Q4

**Comment by bimgeek** [comment]
Hey @trishitapingolia,

 Sorry to inform you that we can't count this model. **The model must be AEC(Architecture, Engineering, Construction) related(a building, house, tower etc.).**

**Comment by horizenight** [comment]
Hey I made a 3d Model of Our (National College of Architecture)  college hostels . Here's the link https://drive.google.com/drive/folders/1Jz5hmzGVVnMzeG_vgagVuW2L3QPzVeWi?usp=sharing
Made it using blender !

**Comment by bimgeek** [comment]
Hey @horizenight ,

Sorry to inform you that we can't count this model. It is a very simplified model with textures applied to mimic detailing. If it had, doors/windows/roofing etc., we would be happy to accept it. Thanks anyway.
