### ISSUE TITLE
GH Docs: Broken links

### ISSUE THREAD

**Issue by fraguada** [specklesystems/speckle-docs#126]
<img width="251" alt="image" src="https://user-images.githubusercontent.com/1014562/195568541-153605c6-4b3b-4f10-9fb5-bf4986aebda0.png">

There are broken links to: 

- https://speckle.guide/user/user/grasshopper.html#create-stream
- https://speckle.guide/user/user/grasshopper.html#get-stream
- https://speckle.guide/user/user/grasshopper.html#list-streams

Maybe these IDs existed before but have since been edited out.

**Comment by AlanRynne** [comment]
OH! these have a duplicated `/user` part that makes them broken... removing one of the `/user` chunks seems to work!

**Comment by fraguada** [comment]
In the md there isn't a dup "user", is was missing the first slash /. Adding this slash seems to do the trick
