### ISSUE TITLE
Add hover effect to FAQs and Core Concepts

### ISSUE THREAD

**Issue by developer-diganta** [specklesystems/speckle-docs#128]
The FAQ and Core Concepts buttons could have a hover effect to make it more user-friendly.
![image](https://user-images.githubusercontent.com/65999534/195983350-307bef68-655e-42ab-9543-f85c31174d99.png)
If this seems to be a relevant issue can I work on it?

**Comment by jsdbroughton** [comment]
What did you have in mind?

**Comment by developer-diganta** [comment]
@jsdbroughton I saw that there is no hover effect when the mouse moves over the button. I guess a slight grayish color would look good?

**Comment by jsdbroughton** [comment]
As it stands we haven’t registered the lack of hover effect in the docs navigation  as a strong need. 

However, If you are looking to contribute a hacktoberfest submission, take a look at the relevant [Project board] the are mix of low code, no code and fully ankle deep issues to help us out with. (https://github.com/orgs/specklesystems/projects/14)
