### ISSUE TITLE
Add path for adding manual accounts in linux

### ISSUE THREAD

**Issue by sanzoghenzo** [specklesystems/speckle-docs#151]
Hi,
I'm starting to use speckle on linux (mainly for QGIS, Blender and my scripts).

I saw that [this discussion](https://speckle.community/t/speckle-manager-for-linux/2953) points to the [instructions to add the account manually](https://speckle.guide/user/manager.html#adding-accounts-manually), but there's no indication of the path used in linux/unix systems. 

After some lurking around the code I discovered that the folder is `~/.local/share/Speckle/Accounts`

It would be great to add this path [to the docs](https://github.com/specklesystems/speckle-docs/blob/b15e81c923fbea4037fc97287eb64a67b3ca4c3e/user/manager.md?plain=1#L50).

**Comment by teocomi** [comment]
Thanks! Paths added :)

One day we should also have a Manager for Linux :)
