### ISSUE TITLE
🏄‍♂️ User Guide: Dynamo, Grasshopper, and a bit of Web

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-docs#3]
Alan is working on general guides for the aforementioned sections, so he has kindly offered to dump these into our lovely user guide when he is finished. 

currently, these live in `/user/connectors.md` but they might get broken out into their own files depending on how it's lookin

**Comment by AlanRynne** [comment]
Merged in PR #6 ! Didn't close this because we still may want to review/change some stuff around.
