### ISSUE TITLE
Docs: Gh to Revit v2

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-docs#43]
Model: 
- start from a cool model, end with a cooler model
- show our tools for what they are valuable: eg parametric facades etc
- I've had a stab at creating a Leadenhall clone you can use as a base (source gh &rh [here](https://drive.google.com/drive/folders/1l2vN5k0R56Hyx2q2vf8cojVd3y0C4kc4?usp=sharing))

Show almost all supported flows and their quirks: 
- reusing existing levels
- creating new levels
- Creating adaptive components
- direct shapes by category
- difference between Revit objects and Speckle objects in schema builder
- updating things, how and when it works
- breps etc

General notes:
- Show rhino/gh and revit side by side updating in real time (where applicable)
- Animations (mp4s -> gifs) should be compelling (think: marketing ready)

**Comment by AlanRynne** [comment]
Forgot to link! Merged in #55
