### ISSUE TITLE
Docs: Revit to Gh and back v2

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-docs#44]
Qualms:
- we can’t even see the revit model
- focus on data processing down the line
- Simple example (for now): colour the model by a revit property of choice (ie, volume; family name and type, etc)
- Complex example (for later if difficult): analysis of sorts and change revit model based on results (eg karamba, or some isovist analysis, or any other practical application) by using the new UpdateParam schema builder component

**Comment by AlanRynne** [comment]
For the simple example, it wouldn't take me more than a day or two to have it ready with nice gifs + intro video.

For the complex example, we'd have to scope it appropriately to not end up loosing a lot of time on it. The structural analysis may require us to model the entire beam/slabs group appropriately for that, which would in turn modify the model in Revit.

Something that could be done quickly would be:
- Setup façade walls in the building
- do a solar analysis with LadyBug
- pass analysis values back to each Revit element.
