### ISSUE TITLE
Tutorial: Create your own web app

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-docs#49]
Title says it all.

**Comment by didimitrie** [comment]
Extra scope: 
- Create a static SPA that allows users to see and query data inside a commit. 
- Data should be displayed in a table view and use pagination. 
- Allow users to build queries with a simple & intuitive "query builder" interface that leverages what the gql api's object `children` endpoint. 
- Persist queries and views in localStorage to allow for later retrieval. 
- CD using netlify or vercel from a github repo
- Show how to integrate with the Speckle Server 

This tutorial can be split up into multiple sections.

**Comment by didimitrie** [comment]
From @AlanRynne, polishing left to do: 
- [ ] code samples (@didimitrie)
- [ ] repo
- [ ] generic polish

**Comment by AlanRynne** [comment]
Closing it up!! Repo is public, with semi-nice readme, and app guide has been merged!
