### ISSUE TITLE
How to get started with Gh video

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-docs#74]
Keep it short and sweet (1-2mins max). Steps to include: 
- [x] installation
- [x] sending data data out 
- [x] view sent data in online viewer
- [x] receiving data

**Comment by AlanRynne** [comment]
Dumped video here! https://drive.google.com/open?id=1-5nGFx9-HR2hlkBcBOJFjiCbUVz7YakO :)
Assets to re-edit are here: https://drive.google.com/drive/folders/1--U7Q8r9fVoT4ztM4O5TLXFEEbTEMYTv

Total duration: 2:30.
