### ISSUE TITLE
Add graphql querying examples

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-docs#98]
From: https://speckle.community/t/graphql-how-to-query-a-speckle-object/1366/5

**Comment by teocomi** [comment]
Time estimate ~10min

**Comment by OliverEGreen** [comment]
I'm not sure I know what to do here, or what's expected of me.

**Comment by teocomi** [comment]
@OliverEGreen please add dim's example on how to query a speckle object to our docs
